mode: preset
voice_id: LIisRj2veIKEBdr6KZ5y
model_id: eleven_flash_v2_5
output_format: mp3_44100_128
streaming_output_format: pcm_24000
optimize_streaming_latency: 3
voice_settings:
  stability: 0.5
  similarity_boost: 0.75
  style: 0.0
  use_speaker_boost: true
